-- UHRATE dev/test schema — derived from the existing (production) Supabase
-- project's live structure, for setting up an ISOLATED dev/test project.
--
-- METHOD: The Supabase CLI could not be used (no authenticated CLI session —
-- no SUPABASE_ACCESS_TOKEN and not logged in — and no raw Postgres database
-- password was available; only the project URL, anon key, and service-role
-- key exist in .env.local, which are HTTP/JWT credentials, not a Postgres
-- wire-protocol connection). A direct `information_schema`/`pg_catalog` SQL
-- connection was equally unavailable for the same reason (no DB password).
--
-- Instead, this was derived from a single, read-only HTTPS GET request to
-- the project's own PostgREST OpenAPI description endpoint
-- (`{SUPABASE_URL}/rest/v1/`, Accept: application/openapi+json), authenticated
-- with the service-role key. This endpoint is generated by PostgREST itself
-- from the live `information_schema`, server-side — it is read-only and does
-- not touch or return any row data. Source Postgres version reported: 14.5.
--
-- CONFIRMED (directly observed from the response):
--   - table names, column names
--   - column data types (as Postgres type names/formats)
--   - nullability (NOT NULL vs nullable)
--   - column defaults (including gen_random_uuid(), now(), literal defaults)
--   - primary keys (PostgREST explicitly annotates PK columns)
--   - absence of any foreign-key relationships: PostgREST annotates FK
--     columns in the same way it annotates PKs, and no such annotation
--     appeared on any column in any of the 11 tables below — consistent
--     with the application code, which joins everything by plain `email`
--     strings rather than DB-level foreign keys.
--
-- NOT CAPTURED (this introspection method cannot expose these; they are
-- deliberately OMITTED below rather than invented):
--   - UNIQUE constraints (e.g. users.email, users.wallet_address,
--     verifications.sha256_hash, verifications.certificate_id,
--     *_registry.registry_id, api_keys.api_key, identity_badges.badge_id,
--     payments.tx_hash, presale_purchases.tx_hash — all of these are
--     treated as effectively-unique by application logic via .eq() lookups
--     and pre-insert duplicate checks, but none of that proves a DB-level
--     UNIQUE constraint actually exists; it was not observable here)
--   - CHECK constraints
--   - indexes beyond the implicit primary-key index
--   - triggers
--   - Row Level Security policies (moot for this app today — every route
--     uses the service-role key, which bypasses RLS regardless — but still
--     a schema component this method can't see)
--   - sequences (none expected/observed; all PKs use gen_random_uuid(), not
--     serial/identity columns)
--   - enums/custom types (none observed among these 11 tables — every
--     column uses a standard built-in Postgres type)
--
-- An additional 12th table, `certificates`, was also found in the live
-- project's exposed schema. It is NOT included below and NOT referenced
-- anywhere in the application code reviewed in this engagement — flagging
-- its existence rather than silently omitting or silently including it.
--
-- gen_random_uuid() is a built-in Postgres 13+ function (no CREATE EXTENSION
-- needed on Postgres 14.5, the version this project reported).

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  full_name text,
  role text DEFAULT 'individual',
  verified_badge boolean DEFAULT false,
  credits integer DEFAULT 10,
  created_at timestamptz DEFAULT now(),
  password_hash text,
  email_verified boolean DEFAULT false,
  verification_token text,
  token_expires_at timestamptz,
  plan_expires_at timestamptz,
  wallet_address text
);

CREATE TABLE wallet_nonces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wallet_address text NOT NULL,
  nonce text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size integer,
  sha256_hash text NOT NULL,
  originality_score integer,
  ai_score integer,
  deepfake_score integer,
  manipulation_score integer,
  trust_score integer,
  rating text,
  blockchain_tx text,
  blockchain_chain text,
  certificate_id text,
  ipfs_hash text,
  created_at timestamptz DEFAULT now(),
  nft_tx text,
  nft_token_id integer,
  nft_contract text,
  user_email text
);

CREATE TABLE document_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registry_id text NOT NULL,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size integer,
  sha256_hash text NOT NULL,
  perceptual_hash text,
  owner_name text NOT NULL,
  owner_email text NOT NULL,
  document_type text NOT NULL,
  chain_id text NOT NULL,
  chain_name text,
  tx_hash text,
  ipfs_hash text,
  metadata text,
  is_original boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE education_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registry_id text NOT NULL,
  institution_name text NOT NULL,
  institution_email text NOT NULL,
  student_name text NOT NULL,
  student_email text NOT NULL,
  degree_type text NOT NULL,
  field_of_study text NOT NULL,
  graduation_year text NOT NULL,
  certificate_number text,
  sha256_hash text,
  chain_id text,
  chain_name text,
  tx_hash text,
  ipfs_hash text,
  is_valid boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE legal_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registry_id text NOT NULL,
  firm_name text NOT NULL,
  firm_email text NOT NULL,
  document_title text NOT NULL,
  document_type text NOT NULL,
  parties text NOT NULL,
  execution_date text NOT NULL,
  jurisdiction text,
  reference_number text,
  sha256_hash text,
  chain_id text,
  chain_name text,
  tx_hash text,
  ipfs_hash text,
  is_valid boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE media_registry (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registry_id text NOT NULL,
  journalist_name text NOT NULL,
  journalist_email text NOT NULL,
  media_organization text,
  content_title text NOT NULL,
  content_type text NOT NULL,
  capture_date text NOT NULL,
  location text,
  description text,
  sha256_hash text,
  chain_id text,
  chain_name text,
  tx_hash text,
  ipfs_hash text,
  is_verified boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tx_hash text NOT NULL,
  plan text NOT NULL,
  payment_method text NOT NULL,
  amount text,
  user_email text NOT NULL,
  from_address text,
  expires_at timestamptz,
  verified boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE presale_purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wallet_address text NOT NULL,
  usdt_amount numeric NOT NULL,
  uhr_amount numeric NOT NULL,
  tx_hash text NOT NULL,
  status text DEFAULT 'pending',
  distributed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE api_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  key_name text NOT NULL,
  api_key text NOT NULL,
  calls_used integer DEFAULT 0,
  calls_limit integer DEFAULT 1000,
  is_active boolean DEFAULT true,
  last_used_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE identity_badges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  full_name text NOT NULL,
  badge_type text NOT NULL,
  organization text,
  website text,
  verification_method text NOT NULL,
  verification_data text,
  is_verified boolean DEFAULT false,
  badge_id text NOT NULL,
  created_at timestamptz DEFAULT now(),
  verified_at timestamptz
);
